### ISSUE TITLE
deserialize/serialize yaml preserving comments and formatting

### ISSUE THREAD

**Issue by flare-ws** [haxsaw/hikaru#28]
```
test1 = hikaru.load_full_yaml(path='./hikaru_test/1.yaml')
print(hikaru.get_yaml(test1[0]))
```

1.yaml
```
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-kiamol-3
spec:
  containers:
  # test_comment
    - name: web # test_comment_2
      image: kiamol/ch02-hello-kiamol
```

output
```
---
apiVersion: v1
kind: Pod
metadata: {name: hello-kiamol-3}
spec:
  containers:
  - {image: kiamol/ch02-hello-kiamol, name: web}
```

Is it possible to preserve comments and formattion (using ruamel.yaml CommentedMap or something similar)? The use case here is quite straightforward - to be able to load, modify and dump k8s objects stored as yamls in a git.
